kind: ConfigMap
apiVersion: v1
metadata:
  name: super-financer-config.json
data:
  config.json: |
    {
      "deploymentConfig": {
        "port": 8080
      },
      "ratelimitConfig": {
        "capacity": 100,
        "rate": "PT1S"
      },
      "databaseConfig": {
        "url": "jdbc:postgresql://postgres-game-service.default.svc.cluster.local/postgres",
        "user": "postgres",
        "password": "1234",
        "driver": "org.postgresql.Driver"
      },
      "jwtConfig": {
        "secret": "secret1",
        "audience": "audience1",
        "issuer": "issuer1",
        "expiresAt": "PT0S"
      },
      "apiVersion": 1
    }
